import type { Metadata } from "next";
import { Exo } from "next/font/google";
import Navbar from "@/components/layout/Navbar/Navbar";
import Footer from "@/components/layout/Footer/Footer";
import 'swiper/css';
import 'swiper/css/free-mode';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import 'swiper/css/thumbs';
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/layout/Providers";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={exo.variable}>
      <body
        className="font-exo"
      >
        <Providers>
          <Navbar/>
        <Toaster position="top-right" />
        {children}
        <Footer/>
        </Providers>

      </body>
    </html>
  );
}
